/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "cpp_project.h"

std::string cpp_project::Greeter::greeting() {
    return std::string("Hello, World!");
}
